spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/datauser?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
      #配置redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    timeout: 3000
    database: 0 #默认是索引为的0的数据库  
mybatis:
  type-aliases-package: com.redis.cache.pojo
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations:
  - classpath:mapper/*.xml
logging:
  level:
    com.redis.cache.mapper.UserMapper: DEBUG

