server:
    port: 8062
spring:
    redis:
        database: 0
        host: localhost
        password: ''
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0
logging:
  level:
      com:
          xulei:
              redis: debug


#logging:
#  level: debug