spring:
  redis:
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        max-wait: 10000
        min-idle: 0
    shutdown-timeout: 1000
    host: 192.168.3.1
    database: 0
    timeout: 300
    port: 6379
server:
  port: 8031

cache.local: true

      
      
